# expose all endpoints:
management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: Random Word Service
    description: Your description here...
    java-vendor: ${java.specification.vendor}
    java-version: ${java.version}